the-toad-tribune/package-lock.json
the-toad-tribune/package.json

1. Install styled components
Closes #6

Install Styled-Components

---

the-toad-tribune/package-lock.json
the-toad-tribune/package.json
the-toad-tribune/src/layout/Ads.tsx
the-toad-tribune/src/layout/Animals.tsx
the-toad-tribune/src/layout/Layout.tsx
the-toad-tribune/src/layout/MainArticle.tsx
the-toad-tribune/src/layout/Movies.tsx
the-toad-tribune/src/layout/Navgation.tsx
the-toad-tribune/src/layout/Politics.tsx
the-toad-tribune/src/layout/Sports.tsx
the-toad-tribune/src/layout/Stonks.tsx
the-toad-tribune/src/layout/Weather.tsx

1. Put each component where it is supposed to be
Creates the initial UI
Used styled component along with grid
Closes #7

Style Layout

---

the-toad-tribune/src/SubApp.tsx
the-toad-tribune/src/api/newsApi.ts
the-toad-tribune/src/layout/Ads.tsx
the-toad-tribune/src/layout/Animals.tsx
the-toad-tribune/src/layout/Layout.tsx
the-toad-tribune/src/layout/MainArticle.tsx
the-toad-tribune/src/layout/Movies.tsx
the-toad-tribune/src/layout/Politics.tsx
the-toad-tribune/src/layout/Sports.tsx
the-toad-tribune/src/layout/Stonks.tsx

1. Setup a page for search results
2. Setup a page for more information
Enhances UI. 
Created three boolean values and three functions to set them accordingly. Created a function to render each ("page") component. Passed the necessary function to each component to allow travel to the more information component.  
Closes #35

Setup Search Page and More Information Page

---

the-toad-tribune/src/SubApp.tsx
the-toad-tribune/src/api/index.ts
the-toad-tribune/src/api/newsApi.ts
the-toad-tribune/src/layout/Animals.tsx
the-toad-tribune/src/layout/Layout.tsx
the-toad-tribune/src/layout/MainArticle.tsx
the-toad-tribune/src/layout/MoreInfo.tsx
the-toad-tribune/src/layout/Movies.tsx
the-toad-tribune/src/layout/Politics.tsx
the-toad-tribune/src/layout/Sports.tsx
the-toad-tribune/src/layout/Stonks.tsx

1. Got the more info page working 
Enable users to learn more about an article
1. Created a MoreInfo component
2. Created a selectedArticle state
3. Created a class to implement an interface for the selectedArticle
4. Created an interface for props for the MoreInfo article
Closes #37

Enable Use of More Info Page

---

the-toad-tribune/src/SubApp.tsx
the-toad-tribune/src/api/index.ts
the-toad-tribune/src/api/weatherApi.ts
the-toad-tribune/src/layout/MainArticle.tsx
the-toad-tribune/src/layout/Weather.tsx

1. Added weatherApi.ts in Api folder.
2. Fetch weather Api using typescript. 
3. Render current location, temperature, time and date in weather component. 
Enable users to see the current locations temperature, time and date in the web app. 
Closes #33

Weather Api

---

the-toad-tribune/src/layout/Politics.tsx

1. Adjust the image, title and description sizes in the politics article to fit the card. 
Enables the user to see the introduction of  Politics article in the card in its proper size. 
Closes #41

Styling the Politics Article

---

the-toad-tribune/src/SubApp.tsx
the-toad-tribune/src/layout/Layout.tsx
the-toad-tribune/src/layout/Navgation.tsx
the-toad-tribune/src/layout/SearchResults.tsx
the-toad-tribune/src/layout/index.tsx

1. Setup search feature
2. Render results on the search page
To enable users to search for articles
1. Created state to house the search results and passed it as props to necessary components
2. Created and adjusted interfaces to pass props as needed
2. Wrote a function to map over search results and render them
3. Used styled-components to style the page and articles
Closes #40

Search Page

---

the-toad-tribune/src/SubApp.tsx
the-toad-tribune/src/layout/Navgation.tsx
the-toad-tribune/src/layout/SearchResults.tsx

1. Enable to use of pagination on the search page
2. Styled the search page 
To allow users to look through many pages of articles
1. Created state values to house the total pages and page number values
2. Made functions to handle page up and down behaviors
3. Styled components for the styling
Closes #48

Search Page Pagination and Styling

---

.vscode/settings.json
the-toad-tribune/src/commons/articleDesign.ts
the-toad-tribune/src/commons/buttons.ts
the-toad-tribune/src/layout/Movies.tsx

1. Create layout design for the Movie Article
2. Add buttons component to Movie article. 
Enable users to read news about Movies or entertainment in the card. 
Closes #29

Movie Article Layout

---

the-toad-tribune/src/SubApp.tsx
the-toad-tribune/src/commons/buttons.ts
the-toad-tribune/src/layout/Animals.tsx
the-toad-tribune/src/layout/MainArticle.tsx
the-toad-tribune/src/layout/Movies.tsx
the-toad-tribune/src/layout/Navgation.tsx
the-toad-tribune/src/layout/Politics.tsx
the-toad-tribune/src/layout/SearchResults.tsx
the-toad-tribune/src/layout/Sports.tsx
the-toad-tribune/src/layout/Stonks.tsx

1. Cursor turns to a pointer when the user hovers on relevant items on page
Enhanced UX
used "cursor: pointer" where necessary 
Closes #54

Make Cursor a Pointer

---

the-toad-tribune/src/SubApp.tsx
the-toad-tribune/src/layout/Navgation.tsx
the-toad-tribune/src/layout/SearchResults.tsx

1. Handled the user input validations in `Navigation.tsx` to check if the user is not putting any empty strings.
2. Refactored the handling when calling the `getNewsEverything` api in `Navigation.tsx` to set the data in a state when there is a successful result.
3. Created an error state to display the errors with styled-components when there are any user input errors in `Navigation.tsx`.
There needs to be a user input validation when they search for news, or if they input an empty string.
To check for user input validations, a state of `validateSearchValue` was created to be used in the `onChange` function instead of the `searchValue` prop so there would not be any errors from all over the app if the user did not input something correctly. All the validations would be handled in …

Handle Search Validations

---

the-toad-tribune/src/layout/MoreInfo.tsx
the-toad-tribune/src/layout/SearchResults.tsx
the-toad-tribune/src/utils/loremIpsum.ts

1. Added styling to the more info page
To enhance user experience
Styled-components
Closes #60

More Info Styling

---

the-toad-tribune/src/layout/MainArticle.tsx
the-toad-tribune/src/layout/Navgation.tsx

1. Create styled components for the Main Article layout. 
Enable users to browse the main article. 
Closes #67

Main Article Layout

---

the-toad-tribune/src/layout/Animals.tsx
the-toad-tribune/src/layout/MainArticle.tsx
the-toad-tribune/src/layout/MoreInfo.tsx
the-toad-tribune/src/layout/Movies.tsx
the-toad-tribune/src/layout/Politics.tsx
the-toad-tribune/src/layout/SearchResults.tsx
the-toad-tribune/src/layout/Sports.tsx
the-toad-tribune/src/layout/Stonks.tsx
the-toad-tribune/src/utils/dateConverter.ts

1. Reformat dates to be easier to read
Enhance UX
Moved a function to a utils folder and imported it everywhere it was needed. 
Closes #71

Convert Publish Dates

---

the-toad-tribune/src/commons/articleDesign2.ts
the-toad-tribune/src/commons/buttons.ts
the-toad-tribune/src/layout/Animals.tsx
the-toad-tribune/src/layout/MainArticle.tsx
the-toad-tribune/src/layout/Movies.tsx
the-toad-tribune/src/layout/Navgation.tsx
the-toad-tribune/src/layout/Politics.tsx
the-toad-tribune/src/layout/Sports.tsx
the-toad-tribune/src/layout/Stonks.tsx
the-toad-tribune/src/layout/Weather.tsx

1. Added titles on every Articles.
2. Fix Layout on Movie Article to make it center. 
3. Format Articles with Prettier. 
Closes #73

Articles Style Adjustments

---

the-toad-tribune/public/index.html
the-toad-tribune/src/commons/articleDesign2.ts
the-toad-tribune/src/layout/MainArticle.tsx
the-toad-tribune/src/layout/Navgation.tsx

1. Pick and assign fonts for the whole app. 
Closes #79

Typography

---

the-toad-tribune/src/SubApp.tsx
the-toad-tribune/src/commons/articleDesign.ts
the-toad-tribune/src/commons/articleDesign2.ts
the-toad-tribune/src/layout/Movies.tsx
the-toad-tribune/src/layout/Politics.tsx

1. Brought the information in the movie component up to the top
2. Aligned content in other components to be aligned on the left rather than the center
To improve UI
Removed align-content center from the movie component
Closes #98

Movie Component Styling 

---

the-toad-tribune/src/layout/MoreInfo.tsx

1. Fix More Info responsive designs at different break points. 
More Info Page should be responsible on all break points. 
Closes #103

Details Page Responsive

---

the-toad-tribune/src/commons/articleDesign2.ts
the-toad-tribune/src/layout/Layout.tsx
the-toad-tribune/src/layout/SearchResults.tsx

1. Fix Search Page responsiveness at all break points. 
Make the search page responsive at all break points. 
Closes #104

Search Page Responsive

---

the-toad-tribune/public/index.html

1. Update font link.
Closes #113

Fix Font Link
